server:
  port: 8081
spring:
  application:
    name: LikeProvider825
  cloud:
    nacos:
      discovery:
        server-addr: 10.8.154.2:8848
  datasource:
    url: jdbc:mysql://localhost:3306/db_cloudoffer?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 825510
    type: com.alibaba.druid.pool.DruidDataSource